config/routes.rb
Rails.application.routes.draw do
  # get "artifacts/index"
  # get "artifacts/show"
  # get "artifacts/new"
  # get "artifacts/edit"

  # root "sessions#new"
  root "homes#index"

  resources :homes

  resources :artifacts

  resources :cohorts do
    get :students
  end

  resources :categories do
    get :subcategories
  end

  resources :searches do
    collection do
      get 'download_file'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :passwords, param: :token
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_resources
  include SearchesHelper

  def search_by_email
    if params[:email].present?
      @results = User.where(email: params[:email]).select(:id, :full_name, :username, :email, :sid, :uuid, :coaching_type,
                :permission_group_id, :prev_permission_group_id, :spec_program, :matriculated_date, :new_competency, :is_ldap, :former_name, :career_interest)
    end
  end

  def index

    if Current.user.coaching_type == "student" and params[:search].nil?
      @results = []
      @results.push Current.user
    elsif params[:search] == '?' or params[:search].to_s == 'help'
      @results = @help
    elsif params[:search].blank?
      redirect_to(root_path, alert: "Empty field! - Please Enter Something!") and return
    elsif params[:search].include? "ohsu.edu"
      @user = User.find_by(email: params[:search])
    elsif params[:search] == 'PhD' or params[:search] == 'MPH' or params[:search] == 'MCR' #current_user.spec_program == "PhD"
      @results = User.where(permission_group_id: 7 ).select(:id, :full_name, :username, :email, :sid, :coaching_type,
                :permission_group_id, :prev_permission_group_id, :spec_program, :matriculated_date, :uuid, :new_competency, :is_ldap, :former_name, :career_interest).order(:full_name)
      params[:search] = 'PhD'  ##use this test in index page or file
      @file_name = hf_create_download_file(@results, params[:search])
    elsif params[:search] == "Wy'east"  #current_user.spec_program == "Wy'east"
      @parameter = params[:search] + "%"
      @results = User.where("coaching_type='student' and spec_program like 'MD/Wy%'")
    elsif params[:search].include? "Med"
      @parameter = "%" + params[:search] + "%"
      permission_group = PermissionGroup.where("title like ?", @parameter)
      if !permission_group.empty?
        #joins_query = "inner join permission_groups on users.permission_group_id = permission_groups.id and permission_groups.title like " + "#{@parameter}" + " order by users.full_name"
        @users = User.where(permission_group_id: permission_group.first.id ).order(:full_name)
        @file_name = hf_create_download_file(@users, params[:search])
      else
        @result = nil
      end
    #     coach_search
    elsif !params[:search].downcase.include? "med18"

      if params[:search].strip.first(2). == 'U0'
        @parameter = params[:search].strip + "%"
        @results = User.where("sid LIKE :search and coaching_type='student' and sid is not null", search: @parameter).select(:id, :full_name, :username, :email, :sid, :uuid, :coaching_type,
                  :permission_group_id, :prev_permission_group_id, :spec_program, :matriculated_date,:new_competency, :former_name, :career_interest).order(:full_name)
      else
          @parameter = params[:search].strip.downcase + "%"
          @users = User.all
          @users = @users.where("lower(full_name) LIKE :search and coaching_type='student' ", search: @parameter).order(:full_name)
      end
    else
      redirect_to(root_path, alert: "No records found for #{params[:search]}")
    end
    respond_to do |format|
        format.html # Normal initial load
        format.turbo_stream # Optional: for more complex UI updates
    end

  end

  def download_file
      if params[:file_name].present?
        private_download params[:file_name]
      end
  end

  private

   def set_resources
     # if session[:aes_key].nil?
     #   aes_key = AES.key
     #   session[:aes_key] = aes_key
     # end

     if File.exist? (Rails.root + "config/search_help.txt")
       file ||= File.read(Rails.root + "config/search_help.txt")
       file = file.gsub("\r\n", "")
       @help = file.html_safe
     else
       @help = "<h4>Missing Help File!</h4".html_safe
     end

   end

   def private_download in_file
      send_file  "#{Rails.root}/tmp/#{in_file}", type: 'text', disposition: 'download'
   end


end

app/helpers/searches_helper.rb
module SearchesHelper

  def hf_format_other_specialty (in_array)
    if in_array.nil? and in_array.empty?
      return []
    end
    if !in_array.last.nil? and in_array.last.include? "Other"
      in_array[-1] = "Other: " + in_array.last.split("~").last
      return in_array
    end
    return in_array
  end

  def hf_check_aes_key
    if session[:aes_key].nil?
      aes_key = AES.key
      session[:aes_key] = aes_key
    end

  end

  def hf_create_download_file(results, permission_group_title)
    file_name = "#{Rails.root}/tmp/#{permission_group_title}_students.txt"
    CSV.open(file_name,'wb', col_sep: "\t") do |csvfile|
      #csvfile << results[0].attributes.keys
      csvfile << ["Student", "Student Email", "UID", "Current Cohort", "Previous Cohort", "Program Status", "Matriculated Date", "NewCompetency", "FormerName"]
      results.each do |result|
          # result.permission_group_id = result.permission_group.title.to_s
          # result.prev_permission_group_id = hf_get_permission_title(result.prev_permission_group_id)
          values_array = []
          values_array << result.full_name
          values_array << result.email
          values_array << result.sid
          values_array << result.permission_group.title.to_s
          values_array << hf_get_permission_title(result.prev_permission_group_id)
          values_array << result.spec_program
          if !result.matriculated_date.nil?
            values_array << result.matriculated_date.strftime("%F")
          else
            values_array << result.matriculated_date
          end
          values_array << result.new_competency
          values_array << result.former_name
          csvfile << values_array
      end
    end

    return File.basename(file_name)
  end

  def hf_get_permission_title(permission_group_id)
    if permission_group_id.nil?
      return ""
    else
      return PermissionGroup.find(permission_group_id).title
    end
  end

  def median(ary)
    middle = ary.size/2
    sorted = ary.sort_by{ |a| a }
    ary.size.odd? ? sorted[middle] : (sorted[middle].to_f + sorted[middle-1].to_f)/2.0
  end

  def get_stats (permission_group_id)
    # result = ActiveRecord::Base.connection.exec_query('select count(user_id)
    #           from epas, users
    #           where involvement <> 0 and
    #                users.id = epas.user_id and
    #                users.spec_program <>' + "'OMFS'" + ' and ' +
    #                'users.permission_group_id = ' + permission_group_id.to_s + '
    #           group by
    #             user_id
    #           order by count DESC')

    wba_count_hash = Epa.joins(:user).where("users.spec_program<>? and users.permission_group_id=?", 'OMFS', permission_group_id.to_s).group(:user_id).count

    return wba_count_hash
  end

  def process_wba_total_count(cohort_id)
    data = {}
    students = User.where(permission_group_id: cohort_id)
    students.each do |student|
      if student.sid != 'U00999999'
        total_count_wbas = User.find_by(sid: student.sid).epas.count
        data.store(student.full_name, total_count_wbas)
      end
    end
    return data
  end

  def hf_wba_stats(user)
    if user.coaching_type == 'student'
      # re-get user records as permission_group_id was pointed to Med21 --> Not sure why!
      user = User.find(user.id)
      cohort_title = user.permission_group.title[/(?<=\().*?(?=\))/]  # to extract cohort Med21
      permission_group_id = user.permission_group_id
      wba_count_hash = get_stats(permission_group_id)

      if wba_count_hash.nil?
          return nil, nil, cohort_title
      else
        #arr = result.rows.flatten  # the array is sorted DESC
        #max = arr.first
        #min = arr.last
        cohort_count = User.where(permission_group_id: permission_group_id).count #excludes BettyBogus
        ave = wba_count_hash.values.sum.to_f/cohort_count.round(2)
        med = median(wba_count_hash.values).round(2)
        return ave, med, cohort_title
      end
    elsif user.coaching_type == 'dean' or user.coaching_type == 'admin'
      cohorts = PermissionGroup.where("id >= ?", 20).order(:title)
      cohorts_stat = {}
      stat = []
      cohorts.each do |cohort|
        title = cohort.title[/(?<=\().*?(?=\))/]
        arr = process_wba_total_count(cohort.id)
        if !arr.empty?
          stat << arr.values.max
          stat << arr.values.min
          stat << arr.values.sum.fdiv(arr.size).round
          stat << median(arr.values).round
          cohorts_stat.store(title, stat)
          stat = []
        end
      end
      return cohorts_stat
    end

  end

  def hf_releaseDate(in_user)

    badgingDates = BadgingDate.find_by(permission_group_id: in_user.permission_group_id)
    if !badgingDates.nil?
      return badgingDates.release_date
    else
      return nil
    end
    #@badge_release_date ||= YAML.load_file("config/badgeReleaseDate.yml")
    # if in_user.permission_group_id == 13
    #   return @badge_release_date["Med21Badge"]["releaseDate"]
    # elsif in_user.permission_group_id == 16
    #   return @badge_release_date["Med22Badge"]["releaseDate"]
    # elsif in_user.permission_group_id == 17
    #   return @badge_release_date["Med23Badge"]["releaseDate"]
    # elsif in_user.permission_group_id == 18
    #   return @badge_release_date["Med24Badge"]["releaseDate"]
    # elsif in_user.permission_group_id == 19
    #   return @badge_release_date["Med25Badge"]["releaseDate"]
    # elsif in_user.permission_group_id == 20
    #   return @badge_release_date["Med26Badge"]["releaseDate"]
    # else
    # end
  end

  def hf_exists_in_FomExam(user_id)
    block_array = []
    blocks = FomExam.where(user_id: user_id).select(:course_code, :permission_group_id).order('course_code, id ASC').uniq
    if blocks.empty?
      blocks = Med22FomExam.where(user_id: user_id).select(:course_code, :permission_group_id).order('course_code ASC').uniq
      if blocks.empty?
        blocks = Med21FomExam.where(user_id: user_id).select(:course_code, :permission_group_id).order('course_code ASC').uniq
      end
    end
    blocks.each do |block|
      block_hash = {}
      if current_user.dean_or_higher?
        block_hash.store("course_code", block.course_code)
      elsif FomLabel.find_by(permission_group_id: block.permission_group_id, course_code: block.course_code).block_enabled
          block_hash.store("course_code", block.course_code)
      else
          block_hash.store("course_code", block.course_code + " - DISABLED!")
      end
      cohort = PermissionGroup.find(block.permission_group_id).title.delete('()').split(" ").last

      block_hash.store("permission_group_id", block.permission_group_id)
      block_hash.store("cohort", cohort)
      block_array.push block_hash
    end

    return block_array
  end

  def hf_exists_in_PreceptorEval(user_id)
    preceptor_evals = PreceptorEval.where(user_id: user_id)
    if preceptor_evals.empty?
      return nil
    else
      permission_group_id = preceptor_evals.first.permission_group_id
      cohort = PermissionGroup.find(permission_group_id).title.delete('()').split(" ").last

      return cohort
    end

  end

  def probe_dataset(lime_survey)
    student_data = []
    student_email_col = lime_survey.student_email_column
    #comp_data = lime_survey.lime_groups.first.lime_questions.first.dataset
    comp_data = lime_survey.dataset
    student_data = comp_data.select {|rec| rec["#{student_email_col}"] == @pk}
    return student_data
  end

  def get_csl_data (in_array)
    temp_array = []
    in_array.each do |data|
      if data.include? "CSL Narrative"
        temp_array.push data
      end
    end
    return temp_array
  end

  def hf_read_tempfile
     if File.file? (Rails.root + "tmp/#{current_user.login}_search.json")
       json_obj = File.read(Rails.root + "tmp/#{current_user.login}_search.json")
       survey_array = JSON.parse(json_obj)
     else
        return nil
     end
  end

  def hf_write_hash(in_hash)
    file_ptr = File.open(Rails.root + "tmp/#{current_user.login}_search.json", 'w')
    file_ptr.write(in_hash.to_json)
    file_ptr.close

  end

  def create_hash (survey_array, username, temp_hash)
      survey_json = []
      user_json = {}
      survey_array.each do |s|
         s_json = {
           "sid" => s.split("~").first,
           "survey" => s.split("~").last
         }
         survey_json << s_json
      end
      temp_hash["#{username}"] = survey_json
      return temp_hash
  end

  def hf_datasets (result, temp_hash)
    survey_array = []
    if result.coaching_type == 'student'

      surveygrps = PermissionLsGroup.where(permission_group_id: result.permission_group_id).order(:updated_at) #result.permission_group.permission_ls_groups
      #surveygrps = surveygrps.sort_by(&:updated_at)
      if !result.prev_permission_group_id.nil?
        prev_surveygrps = PermissionLsGroup.where(permission_group_id: result.prev_permission_group_id).order(:updated_at)
        surveygrps = (surveygrps + prev_surveygrps)
      end

      surveygrps.each do |s|
        survey = s.lime_survey.title
        sid = s.lime_survey.sid
        if current_user.superadmin? and !probe_dataset(s.lime_survey).empty?
          survey_array.push sid.to_s + "~" + survey
        #elsif survey.include? "Graph View" or survey.include? "Remediation" or survey.include? "Core Clinical/Electives"

        else
          if !probe_dataset(s.lime_survey).empty?
              survey_array.push sid.to_s + "~" + survey
           end
        end
      end
      #store surveys in session variable
      session[:search] ||= []
      session[:search] = nil
      session[:search] = get_csl_data(survey_array)

      survey_array = survey_array.uniq

      temp_hash = create_hash(survey_array, result.login, temp_hash)


      return survey_array
     else
      return ["Not Applicable"]
     end
  end

  def hf_graph_type (dataset)
    if dataset.include? "Core Clinical" or dataset.include? "Remediation"

app/views/searches/_card_results.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @temp_hash = {} %>
  <% @results.each do |result| %>
   <div class="col">
    <div class="card" style="width: 600px">
      <div class="card-body">
           <span class="caret"><b><%= result.full_name %></b></span>
            <ul class="nested">
              <li>
                <table class="table table-hover main-table table-light responsive-sm">
                  <% if ['chungp', 'fruhwirt', 'dunnbri', 'schneibe', 'itot'].include? current_user.username %>
                    <tr><td style="text-align:left">Email</td><td style="color:brown"><%= link_to result.email.to_s, update_loa_users_path(email: result.email), class: "nav-link blue-text" ,target: :_blank %></td></tr>
                    <tr><td style="text-align:left">SID</td><td> <%= link_to result.sid.to_s, update_loa_users_path(sid: result.sid), class: "nav-link blue-text", target: :_blank %></td></tr>
                  <% else %>
                      <tr><td style="text-align:left">Email</td><td style="color:brown"><%= result.email %> </td></tr>
                      <tr><td style="text-align:left">SID</td><td><%= result.sid %> </td></tr>
                  <% end %>

                  <tr><td style="text-align:left">Current Cohort</td><td><%= result.permission_group.title.to_s  %> </td></tr>
                  <tr><td style="text-align:left">Previous Cohort</td><td><%= hf_get_permission_title(result.prev_permission_group_id)  %> </td></tr>
                  <tr><td style="text-align:left">Program Status</td><td><%= result.spec_program %> </td></tr>
                  <tr><td style="text-align:left">Matriculated Date</td><td><%= result.matriculated_date.to_s %> </td></tr>
                  <tr><td style="text-align:left">New Competency</td><td style="color:red"><%= result.new_competency? ? 'Yes' : 'No' %> </td></tr>
                  <tr><td style="text-align:left">Former Name</td><td><%= result.former_name %> </td></tr>
                  <tr><td style="text-align:left"><%= link_to "Specialties Interest (Click to update)".html_safe, update_career_interests_users_path(uuid: result.uuid),  target: :_blank %> </td>
                    <td style="color:blue"><%= raw(hf_format_other_specialty(result.career_interest).each_with_index.map{ |item, index| "#{index + 1}. #{item}" }.join("<br>")) %></td></tr>
                  <tr>
                    <% bls_record = result.ume_bls %>
                    <% if !bls_record.nil? %>
                       <% if bls_record.expiration_date.after? (Date.today) %>
                           <td style="text-align:left">BLS ExpDate</td><td style="color:green"> <b><%= bls_record.expiration_date.strftime("%F") %></b></td>
                       <% else %>
                           <td style="text-align:left">BLS ExpDate</td><td style="color:red"> <b><%= bls_record.expiration_date.strftime("%F") %></b></td>
                       <% end %>
                    <% else %>
                        <td style="text-align:left">BLS ExpDate</td><td style="color:red"><b>No BLS Data</b></td>
                    <% end %>
                  </tr>
                  <tr><td style="text-align:left"># of WBAs (All levels)</td><td style="color:purple"><b><%= result.epas.where.not(involvement: 0).count.to_s %></b></td></tr>
                  <% if result.new_competency? %>
                    <% no_of_badges = result.epa_masters.where("epa not in ('EPA12', 'EPA13') and status = ? and status_date < ?",'Badge', hf_releaseDate(result)).count.to_s  %>
                  <% else %>
                    <% if result.spec_program.include? "Paused badging" %>
                      <% no_of_badges = 0 %>
                    <% else %>
                      <% no_of_badges = result.epa_masters.where("status = ? and status_date < ?",'Badge', hf_releaseDate(result)).count.to_s  %>
                    <% end %>
                  <% end %>
                  <tr><td style="text-align:left"># of Badges Awarded</td><td style="color:purple"><b><%= no_of_badges %></b></td></tr>
                </table>
              </li>

              <li><span class="caret">Datasets</span>
                <ul class="nested">
                  <li><%= link_to("<b>View Artifacts</b>".html_safe, artifacts_path(uuid: result.uuid), class: "nav-link blue-text", target: '_blank')  %> </li>
                  <% if result.new_competency? #and result.username == 'peterbogus' %>
                    <li><%= link_to("<b>Clinical Phase Dataset</b>".html_safe, user_new_competencies_path(user_id: result.id), class: "nav-link link-to-text-color", target: '_blank') %></li>
                  <% else %>
                    <li><%= link_to("<b>Clinical Phase Dataset</b>".html_safe, user_competencies_path(user_id: result.id), class: "nav-link link-to-text-color", target: '_blank') %></li>
                  <% end %>
                  <li><%= link_to("<b>Overall Progress on Badges/WBAs..</b>".html_safe, user_overall_progresses_path(user_id: result.id), class: "nav-link link-to-text-color", target: '_blank') %></li>
                  <li><%= link_to("<b>Detail WBAs Listing</b>".html_safe, epas_path(uuid: result.uuid), class: "nav-link link-to-text-color", target: '_blank') %></li>

                    <% fom_block_array = [] %>
                    <%  hf_exists_in_FomExam(result.id).each do |block| %>
                        <% cohort = block["cohort"] %>
                        <% permission_group_id = block["permission_group_id"] %>
                        <% course_code = block["course_code"] %>

                        <% if !course_code.include? "DISABLED" %>
                          <% session[:attach_id] = -1 %>
                          <% hf_check_aes_key %>

                          <% fom_block_array.push course_code %>
                          <li><%= link_to("<b>#{cohort}:Foundation of Medicine: #{course_code}</b>".html_safe,
                                  display_fom_fom_exams_path(permission_group_id: AES.encrypt(permission_group_id.to_s, session[:aes_key]), course_code: AES.encrypt(course_code, session[:aes_key] ),
                                  uuid: result.uuid), method: :get, class: "nav-link blue-text", target: '_blank') %> </li>
                        <% else %>
                           <li><%= sanitize "<b>#{cohort}:Foundation of Medicine: #{course_code}</b><br />".html_safe %></li>
                        <% end %>
                    <% end %>
                    <% cohort = hf_exists_in_PreceptorEval(result.id) %>

                    <% if !cohort.blank? %>
                      <%= link_to("<b>#{cohort}:Foundation of Medicine: Preceptorship Evaluations</b>".html_safe,
                              preceptor_eval_path(uuid: result.uuid), class: "nav-link blue-text", target: '_blank') %> <br>
                    <% end %>

                    <% if hf_has_csl_feedbacks(result.id) %>
                      <% session[:user_id] = result.id %>
                      <% session[:cohort] = cohort_title(result.permission_group_id) %>
                      <%= link_to('<i><b>CSL Feedback from Qualtrics</b></i>'.html_safe, csl_feedbacks_index_path(user_id: result.id), class: "nav-link blue-text", target: '_blank') %>
                      <br>

                    <% end %>

                    <% hf_datasets(result, @temp_hash).each do |dataset| %>
                       <% sid = dataset.split("~").first %>
                       <% if !dataset.split("~").last.include? "Core Clinical/Electives" %>
                          <% if !fom_block_array.include? dataset.split(":").last %>
                             <%= link_to dataset.split("~").last, polymorphic_path([hf_graph_type(dataset).to_sym, :ls_report], sid: sid, pk: @pk), target: '_blank',
                              class: "modal-click", 'data-bs-target': '#modal-dataset' %> <br>
                          <% end %>
                      <% end %>
                    <% end %>

                    <% if ['chungp','fruhwirt','meltond', 'nmai' ].include? current_user.username %>
                      <%= link_to '<i class="fa fa-cog" style="color:#23A9BD"></i> Add USMLE/Step Exams'.html_safe, usmle_exams_path(user_id: result.id, full_name: result.full_name),
                      target: '_blank', class: "nav-link blue-text" %>
                    <% end %>

                    <% if ['dean', 'admin'].include? current_user.coaching_type  %>
                      <% precep_count = User.find(result.id).precep_meetings.count %>
                      <% if precep_count == 0 %>
                      <%= link_to '<i class="fa fa-cog" style="color:#23A9BD"></i> Preceptorship Meetings'.html_safe,
                          precep_meetings_path(user_id: result.id), target: '_blank', class: "nav-link blue-text" %>
                      <% else %>
                        <% html_str = "<i class='fa fa-cog' style='color:#23A9BD'></i> Preceptorship Meetings <span class='badge bg-danger'>" + precep_count.to_s + "</span>" %>
                        <%= link_to html_str.html_safe, precep_meetings_path(user_id: result.id), target: '_blank', class: "nav-link blue-text" %>
                      <% end %>
                    <% end %>

                </ul>
              </li>
            </ul>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/searches/_cohort_listing.html.erb
<div class="d-flex align-items-center gap-2 mt-0 mb-2">
  <h5 class="text-primary mb-0">Search Result -</h5>

  <%= link_to download_file_searches_path(file_name: @file_name),
              class: "d-inline-flex align-items-center" do %>&nbsp; Download
    <i class="bi bi-download"></i>
  <% end %>
</div>

<div data-controller="datatable">
  <table data-datatable-target="table" class="table table-striped">
      <thead>
        <tr>
          <th style="text-align:center">Student</th>
          <th style="text-align:center">Student Email </th>
          <th style="text-align:center">UID </th>
          <th style="text-align:center">Current Cohort</th>
          <th style="text-align:center">Previous Cohort</th>
          <th style="text-align:center">Program Status</th>
          <th style="text-align:center">Matriculated Date</th>
          <th style="text-align:center">New Comp</th>
          <th style="text-align:center">NetAccess</th>
          <th style="text-align:center">Former Name</th>
          <th style="text-align:center">Specialty Interests</th>
        </tr>
      </thead>
      <% results.each do |result| %>
        <tr>
          <td class="text-center"><%= link_to result.full_name, searches_path(search: result.email), target: :blank %></td>
          <td class="text-center"><%= result.email %></td>
          <% if ['chungp', 'fruhwirt', 'dunnbri', 'schneibe'].include? Current.user.username %>
            <td class="text-center"><%= link_to result.sid.to_s, update_loa_users_path(sid: result.sid), target: :_blank %></td>
          <% else %>
            <td class="text-center"><%= result.sid.to_s  %></td>
          <% end %>
          <td class="text-center"><%= result.permission_group.title.to_s %></td>
          <td class="text-center"><%= hf_get_permission_title(result.prev_permission_group_id) %></td>
          <td class="text-center"><%= result.spec_program %></td>
          <% if !result.matriculated_date.nil? %>
            <td class="text-center"><%= result.matriculated_date.strftime("%F") %></td>
          <% else %>
            <td></td>
          <% end %>
          <td class="text-center"><%= result.new_competency? ? 'Yes' : '<b style="color:red">No</b>'.html_safe %></td>
          <td class="text-center"><%= result.is_ldap? ? 'Yes' : '<b style="color:red">No</b>'.html_safe %></td>
          <td class="text-center"><%= result.former_name %></td>
          <td class="text-center"><%= result.career_interest.join(", ") %></td>
        </tr>
      <% end %>
  </table>
</div>

app/views/searches/_results.html.erb
<% if users.any? %>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @users.each do |student| %>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title text-primary"><%= link_to student.full_name, searches_path(search: student.email), target: :blank %></h5>
          <p class="card-text text-muted">Email: <strong><%= student.email %></strong></p>
          <p class="card-text text-muted">Student Uid: <strong><%= student.sid %></strong></p>
          <p class="card-text text-muted">Matriculated Date: <strong><%= student.matriculated_date %></strong></p>
          <p class="card-text text-muted">Current Cohort: <strong><%= student.permission_group.title %></strong></p>

        </div>
      </div>
    </div>
  <% end %>
</div>
<% else %>
  <p class="text-muted">No results found.</p>
<% end %>

app/views/searches/download_file.html.erb
<h1>Searches#download_file</h1>
<p>Find me in app/views/searches/download_file.html.erb</p>

app/views/searches/index.html.erb
<!-- <div id="search-results">
  <%#= render partial: "results" %>
</div> -->

<turbo-frame id="results">
  <% if !params[:search].nil? and (params[:search].include? "Med" or params[:search] == 'PhD') %>
    <%= render partial: 'cohort_listing', locals: {results: @users} %>
  <% elsif !params[:search].nil? and (params[:search].include? "ohsu.edu" )    %>
    <%= render "homes/student_profile", welcome_msg: "Student: #{@user.display_name}", user: @user %>
  <% elsif @users.count == 1  %>
    <%= render "homes/student_profile", welcome_msg: "Student: #{@users.first.display_name}", user: @users.first %>
  <% else %>
      <%= render "results", users: @users %>
  <% end %>
</turbo-frame>

app/views/searches/index.turbo_stream.erb
<turbo-stream target="results">
  <template>
    <%= render "results", users: @users %>
  </template>
</turbo-stream>