config/routes.rb
Rails.application.routes.draw do
  # get "artifacts/index"
  # get "artifacts/show"
  # get "artifacts/new"
  # get "artifacts/edit"

  # root "sessions#new"
  root "homes#index"

  resources :homes

  resources :artifacts

  resources :cohorts do
    get :students
  end

  resources :categories do
    get :subcategories
  end

  resources :searches do
    collection do
      get 'download_file'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :passwords, param: :token
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "REDEI V8" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <!-- DataTables CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css"> -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script> -->
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light-green mb-4 sticky-top shadow-sm">
      <div class="container">
        <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <%= image_tag "OHSU-RGB-4C-POS.png",
                      alt: "Logo",
                      height: "32",
                      class: "me-2" %>
        REDEI V8
      <% end %>
        <div class="navbar-nav ms-auto">
          <% if Current.user %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to "Home", root_path, class: "nav-link #{'active' if current_page?(root_path)}" %>
                </li>
            </ul>

            <span class="nav-link text-light">Welcome, <%= Current.user.display_name %>!</span>

            <% if Current.user.coaching_type == 'dean' %>
              <%= form_with url: searches_path, method: :get, class: "d-flex me-3", local: true,
                    data: { turbo_frame: "results"
                } do |form| %>
                <%= form.label :search, "Student/Cohort Search", class: "form-control" %>
                <%= form.text_field :search,
                      class: "form-control form-control-sm me-2",
                      placeholder: "Search Student LastName…" %>
              <% end %>
            <% end %>

            <%= button_to "Logout",
                session_path,
                method: :delete,
                data: { turbo: false },
                class: "dropdown-item" %>
          <% else %>
            <%= link_to "Login", new_session_path, class: "nav-link" %>
          <% end %>
        </div>
      </div>
    </nav>

    <main class="container-fluid pt-1">
      <%= yield %>
    </main>

  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "REDEI V8" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-light">
    <main class="container py-5">
      <%= yield %>
    </main>
  </body>
</html>